spring:
    application:
        name: greatPlan
    # 延时停机时长
    lifecycle:
        timeout-per-shutdown-phase: 30s
server:
    # 服务端口
    port: 8080
    # 延时停机
    shutdown: graceful
    servlet:
        # 上下文起始路径
        context-path: /
        # 编码
        encoding:
            enabled: true
            charset: UTF-8
            force: true
# 补充包配置
plugin:
    # 插件源码目录
    source-dir: src/main/java/com/ljf/greatplan/docking/plugins
#    source-dir: classes/com/ljf/greatplan/docking/plugins
    # 插件资源目录
    resource-dir: src/main/resources/static/plugins
#    resource-dir: classes/static/plugins
    # 允许注册至核心包的资源文件格式白名单
    pass-format: .html,.css,.js
