spring:
    application:
        name: greatPlan
    # 延时停机时长
    lifecycle:
        timeout-per-shutdown-phase: 30s
server:
    # 服务端口
    port: 8080
    # 延时停机
    shutdown: graceful
    servlet:
        # 上下文起始路径
        context-path: /
        # 编码
        encoding:
            enabled: true
            charset: UTF-8
            force: true
# 插件配置
plugin:
    # 插件资源
    root-dir: D:\planOfElectronicHamster\9，GreatPlan\4，第四次尝试（进行中）\greatPlan\src\main\java\com\ljf\greatplan\docking\plugins
    # 插件资源映射
    runtime-dir: D:\planOfElectronicHamster\9，GreatPlan\4，第四次尝试（进行中）\greatPlan\plugins-runtime
    # 格式白名单
    pass-format: .html,.css,.js